from Organizations.GeneratePrice.Entities.Fields.Barcode import Barcode
from Organizations.GeneratePrice.Entities.NomenclatureMarket import NomenclatureMarket
from Organizations.GeneratePrice.Entities.Fields.Product import Product


class NomenclatureCafeMarket(NomenclatureMarket):
    def __init__(self):
        super().__init__()

    def _init_price(self) -> dict[str, list[Product]]:
        return {
            "drinks": [
                Product("Чай", "drinks", "budget", 35.0, Barcode()),
                Product("Лимонад", "drinks", "middle", 50.0, Barcode()),
                Product("Кофе", "drinks", "premium", 70.0, Barcode()),
                Product("Какао", "drinks", "middle", 60.0, Barcode()),
                Product("Дюшес", "drinks", "middle", 100.0, Barcode()),
                Product("Коктейль «Летний»", "drinks", "premium", 170.0, Barcode()),
                Product("Чай травяной", "drinks", "budget", 100.0, Barcode()),
                Product("Чай «Лесные ягоды»", "drinks", "middle", 120.0, Barcode()),
                Product("Латте", "drinks", "premium", 180.0, Barcode()),
                Product("Малиновый раф", "drinks", "budget", 340.0, Barcode()),
                Product("Раф на кокосовом молоке", "drinks", "middle", 400.0, Barcode()),
                Product("Латте на банановом молоке", "drinks", "premium", 450.0, Barcode()),
                Product("Чай зеленый", "drinks", "budget", 45.0, Barcode()),
                Product("Чай черный", "drinks", "middle", 50.0, Barcode()),
                Product("Чай ягодный", "drinks", "premium", 65.0, Barcode()),
                Product("Капучино", "drinks", "middle", 110.0, Barcode()),
                Product("Молочный коктейль", "drinks", "premium", 160.0, Barcode()),
                Product("Лимонный коктейль", "drinks", "premium", 250.0, Barcode()),
                Product("Морс", "drinks", "budget", 55.0, Barcode()),
                Product("Лимонад с топиокой", "drinks", "middle", 220.0, Barcode()),
                Product("Бабл-ти с джус-боллами", "drinks", "premium", 350.0, Barcode()),
                Product("Байкал", "drinks", "premium", 75.0, Barcode()),
                Product("Тархун", "drinks", "budget", 110.0, Barcode()),
                Product("Коктейль «К ребрам»", "drinks", "middle", 200.0, Barcode()),
                Product("Лимонад «Арбуз-мята»", "drinks", "premium", 280.0, Barcode()),
                Product("Арбуз-дыня", "drinks", "budget", 100.0, Barcode()),
                Product("Лимонад Таро", "drinks", "middle", 170.0, Barcode()),
                Product("Кола", "drinks", "budget", 100.0, Barcode()),
            ],
            "snacks": [
                Product("Картофель Фри", "snacks", "budget", 65.0, Barcode()),
                Product("Салат «Свежий»", "snacks", "middle", 90.0, Barcode()),
                Product("Гирос", "snacks", "premium", 170.0, Barcode()),
                Product("Салат «Витаминный»", "snacks", "budget", 50.0, Barcode()),
                Product("Салат «Оливье»", "snacks", "premium", 95.0, Barcode()),
                Product("Чесночные гренки", "snacks", "budget", 150.0, Barcode()),
                Product("Куриные крылышки", "snacks", "middle", 220.0, Barcode()),
                Product("Сырная тарелка", "snacks", "premium", 400.0, Barcode()),
                Product("Блинчики", "snacks", "budget", 110.0, Barcode()),
                Product("Оладушки из кабачков", "snacks", "middle", 170.0, Barcode()),
                Product("Креветки во фритюре", "snacks", "premium", 330.0, Barcode()),
                Product("Жюльен", "snacks", "budget", 340.0, Barcode()),
                Product("Карпаччо", "snacks", "middle", 450.0, Barcode()),
                Product("Тар-тар", "snacks", "premium", 570.0, Barcode()),
                Product("Оладушки", "snacks", "premium", 120.0, Barcode()),
                Product("Наггетсы", "snacks", "middle", 100.0, Barcode()),
                Product("Сырные палочки", "snacks", "premium", 130.0, Barcode()),
                Product("Салат Греческий", "snacks", "budget", 350.0, Barcode()),
                Product("Салат Цезарь", "snacks", "middle", 550.0, Barcode()),
                Product("Салат Нисуаз", "snacks", "premium", 600.0, Barcode()),
                Product("Сырные шарики", "snacks", "budget", 110.0, Barcode()),
                Product("Кальмары в кляре", "snacks", "middle", 200.0, Barcode()),
                Product("Креветки в кляре", "snacks", "premium", 250.0, Barcode()),
                Product("Рыбное ассорти", "snacks", "middle", 310.0, Barcode()),
                Product("Ассорти сыров", "snacks", "premium", 400.0, Barcode()),
                Product("Онигири с тунцом", "snacks", "budget", 150.0, Barcode()),
                Product("Корн-дог с сосиской", "snacks", "middle", 250.0, Barcode()),
                Product("Корн-дог с сыром", "snacks", "premium", 310.0, Barcode()),
                Product("Крылышки", "snacks", "middle", 160.0, Barcode()),
                Product("Ножки", "snacks", "premium", 220.0, Barcode()),
                Product("Салат Оливье", "snacks", "middle", 160.0, Barcode()),
                Product("Свиная нарезка", "snacks", "premium", 390.0, Barcode()),
                Product("Онигири с огурцом", "snacks", "budget", 90.0, Barcode()),
                Product("Кимпаб с тунцом", "snacks", "premium", 300.0, Barcode()),
                Product("Стрипсы", "snacks", "premium", 200.0, Barcode()),
            ],
            "entrees": [
                Product("Шаурма с курицей", "entrees", "budget", 150.0, Barcode()),
                Product("Шаурма со свининой", "entrees", "middle", 200.0, Barcode()),
                Product("Шаурма с говядиной", "entrees", "premium", 250.0, Barcode()),
                Product("Борщ", "entrees", "budget", 100.0, Barcode()),
                Product("Макароны с рыбой", "entrees", "middle", 120.0, Barcode()),
                Product("Пюре с котлетой", "entrees", "premium", 140.0, Barcode()),
                Product("Люля из курицы", "entrees", "budget", 180.0, Barcode()),
                Product("Шашлык из баранины", "entrees", "middle", 250.0, Barcode()),
                Product("Цыпленок Тапака", "entrees", "premium", 370.0, Barcode()),
                Product("Карбонара", "entrees", "budget", 300.0, Barcode()),
                Product("Бефстроганов", "entrees", "middle", 350.0, Barcode()),
                Product("Жаркое из телятины", "entrees", "premium", 390.0, Barcode()),
                Product("Стейк из лосося", "entrees", "budget", 520.0, Barcode()),
                Product("Филе Сибаса", "entrees", "middle", 600.0, Barcode()),
                Product("Медальоны из говядины", "entrees", "premium", 760.0, Barcode()),
                Product("Картофель с куриной котлетой", "entrees", "budget", 110.0, Barcode()),
                Product("Макароны с свиной отбивной", "entrees", "middle", 170.0, Barcode()),
                Product("Борщ с пампушками и чесночным маслом", "entrees", "premium", 185.0, Barcode()),
                Product("Пицца Маргарита", "entrees", "budget", 400.0, Barcode()),
                Product("Пицца Пепперони", "entrees", "middle", 470.0, Barcode()),
                Product("Пицца Мясная", "entrees", "premium", 550.0, Barcode()),
                Product("Пицца Грибная", "entrees", "budget", 390.0, Barcode()),
                Product("Пицца Домашняя", "entrees", "premium", 580.0, Barcode()),
                Product("Судак с пюре", "entrees", "budget", 380.0, Barcode()),
                Product("Крем-суп грибной", "entrees", "middle", 470.0, Barcode()),
                Product("Утиное филе с яблоками", "entrees", "premium", 550.0, Barcode()),
                Product("Ролл Сяке Маки", "entrees", "budget", 220.0, Barcode()),
                Product("Ролл Калифорния", "entrees", "middle", 300.0, Barcode()),
                Product("Ролл Филадельфия", "entrees", "premium", 340.0, Barcode()),
                Product("Люля из свинины", "entrees", "middle", 250.0, Barcode()),
                Product("Судак запеченный", "entrees", "budget", 270.0, Barcode()),
                Product("Стейк лосося", "entrees", "premium", 550.0, Barcode()),
                Product("Жареный рис с морепродуктами", "entrees", "budget", 350.0, Barcode()),
                Product("Рамен с кимчи", "entrees", "middle", 400.0, Barcode()),
                Product("Том ям", "entrees", "premium", 550.0, Barcode()),
                Product("Чизбургер", "entrees", "budget", 90.0, Barcode()),
                Product("Бургер с курицей", "entrees", "middle", 130.0, Barcode()),
                Product("Бургер с свиной котлетой", "entrees", "premium", 170.0, Barcode()),
                Product("Пельмени со свининой", "entrees", "budget", 180.0, Barcode()),
                Product("Пельмени домашние", "entrees", "middle", 230.0, Barcode()),
                Product("Пельмени с говядиной", "entrees", "premium", 290.0, Barcode()),
                Product("Ребра №1", "entrees", "budget", 450.0, Barcode()),
                Product("Ребра с барбекю", "entrees", "middle", 670.0, Barcode()),
                Product("Ребра XXXL", "entrees", "premium", 890.0, Barcode()),
                Product("Удон с курицей", "entrees", "budget", 220.0, Barcode()),
                Product("ФоБо", "entrees", "premium", 470.0, Barcode()),
                Product("Крабсбургер", "entrees", "middle", 200.0, Barcode()),
                Product("Бифбургер", "entrees", "premium", 240.0, Barcode()),
            ],
            "desserts": [
                Product("Пирожок с яблоком", "desserts", "budget", 50.0, Barcode()),
                Product("Медовик", "desserts", "middle", 100.0, Barcode()),
                Product("Пахлава", "desserts", "premium", 150.0, Barcode()),
                Product("Повидло", "desserts", "budget", 30.0, Barcode()),
                Product("Пирожок с вишней", "desserts", "middle", 45.0, Barcode()),
                Product("Наполеон", "desserts", "premium", 80.0, Barcode()),
                Product("Мороженое", "desserts", "budget", 70.0, Barcode()),
                Product("Чизкейк", "desserts", "premium", 180.0, Barcode()),
                Product("Сорбет", "desserts", "budget", 120.0, Barcode()),
                Product("Милфей", "desserts", "middle", 200.0, Barcode()),
                Product("Тирамису", "desserts", "premium", 260.0, Barcode()),
                Product("Панна-Котта", "desserts", "budget", 350.0, Barcode()),
                Product("Павлова", "desserts", "middle", 400.0, Barcode()),
                Product("Брауни", "desserts", "premium", 470.0, Barcode()),
                Product("Печенье", "desserts", "budget", 35.0, Barcode()),
                Product("Мармелад", "desserts", "middle", 55.0, Barcode()),
                Product("Блины с яблоками", "desserts", "budget", 220.0, Barcode()),
                Product("Блины с ягодами", "desserts", "middle", 300.0, Barcode()),
                Product("Сладкий ролл с бананом", "desserts", "budget", 170.0, Barcode()),
                Product("Сладкий ролл с клубникой", "desserts", "middle", 185.0, Barcode()),
                Product("Моти с клубникой", "desserts", "budget", 135.0, Barcode()),
                Product("Моти юдзу", "desserts", "middle", 150.0, Barcode()),
                Product("Муссовый хомяк", "desserts", "premium", 350.0, Barcode()),
                Product("Пирожное Картошка", "desserts", "budget", 50.0, Barcode()),
                Product("Чизкейк с малиной", "desserts", "middle", 240.0, Barcode()),
                Product("Чизкейк с манго", "desserts", "premium", 310.0, Barcode()),
                Product("Моти с бананом", "desserts", "budget", 120.0, Barcode()),
                Product("Моти орео", "desserts", "middle", 145.0, Barcode()),
                Product("Ванильный котик", "desserts", "premium", 270.0, Barcode()),
                Product("Маффин", "desserts", "budget", 70.0, Barcode()),
                Product("Сладкий пирожок", "desserts", "middle", 75.0, Barcode()),
            ]
        }
